### ISSUE TITLE
If ssh key not deployed on server, resulting pw prompt and script exit causes Mac xterm to stop rendering typed text.

### ISSUE THREAD

**Issue by joshjriley** [KeckObservatory/RemoteObserving#80] opened 2020-10-06 01:25 UTC
If validate_ssh_key fails b/c key does not exist on server, it prompts for kvnc pass which times out in 5 seconds.  When app exits on its own as a result, it results in my Mac term not displaying any typed text.  Term still works though.  Not sure if this is just an issue with my Mac xterm or any mac or linux xterm.  My guess is something to do with needing to terminate the subprocess properly which is still waiting for text password input.

**Comment by joshwalawender** [comment] 2023-11-22 22:04
I've not seen this reproduced and there have been lots of changes since this was raised, so I'm closing this in the hopes it has gone away.

**Closed as completed by joshwalawender** 2023-11-22 22:04 UTC
